### ISSUE TITLE
Add Windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/backports.lzma-feedstock#1]
Was unable to build Windows successfully in staged-recipes. For reference, here is [AppVeyor's build logs]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.11341 ). It appears that upstream has [not tested Windows]( https://github.com/peterjc/backports.lzma/tree/565834034166c809fec9d54a20f0c95f9387fb36#supported-platforms ). Though it seems @carlkl [mentioned]( https://github.com/peterjc/backports.lzma/issues/14 ) he was able to build [Windows wheels]( https://anaconda.org/carlkl/backports.lzma ). Maybe he can offer us info about how he was able to do this.

**Comment by jakirkham** [comment]
xref: https://github.com/peterjc/backports.lzma/issues/14#issuecomment-281441697

**Comment by jakirkham** [comment]
As part of this, we will need a copy of `xz` that we can use with Visual Studio 2008. This can either be handled by building it as part of the `backport.lzma` build or it can be built against an `xz` package that will work. Raised issue ( https://github.com/conda-forge/xz-feedstock/issues/14 ) to explore the latter.

**Comment by carlkl** [comment]
xz-5.2.3 can be compiled with the help of msys2/mingw-w64

```
./configure --enable-static --disable-shared --disable-rpath --disable-lzma-links --enable-threads=vista --prefix=/<PATH>
make
make install
```
Using the static library should be preferred in this case as the library will be linked into the _lzma.pyd binary.

**Comment by carlkl** [comment]
Easier to deploy. If you want to deploy `liblzma.dll` as a dependency of  `_lzma.pyd` you have to put this dll alongside `_lzma.pyd`. 

HINT: Configuring with `--enable-threads=vista` is important for xz-5.2.3, otherwise you wil encounter errors during make. `--disable-threads` is also an option to consider.
